// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA12B6wvY8FNyjyD7RxKFlyrn1L974k6pg',
    appId: '1:337198593597:web:c426e30a31af3e71b4dc54',
    messagingSenderId: '337198593597',
    projectId: 'tanapa-a7da5',
    authDomain: 'tanapa-a7da5.firebaseapp.com',
    storageBucket: 'tanapa-a7da5.appspot.com',
    measurementId: 'G-1040SE1JN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMruYX_PPhEe8onaBA9DJNHjKzDCHh2B0',
    appId: '1:337198593597:android:8152504e3ea27325b4dc54',
    messagingSenderId: '337198593597',
    projectId: 'tanapa-a7da5',
    storageBucket: 'tanapa-a7da5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIy5Q0vzT6JQ15weOdRVYXIeB6BuUd3hE',
    appId: '1:337198593597:ios:0667330913fe00cbb4dc54',
    messagingSenderId: '337198593597',
    projectId: 'tanapa-a7da5',
    storageBucket: 'tanapa-a7da5.appspot.com',
    iosClientId: '337198593597-tsrl6isos7fqd2o6e69dn38colav0phu.apps.googleusercontent.com',
    iosBundleId: 'com.example.tanapa',
  );
}
